### ISSUE TITLE
When DPI is not 100%, the modern toolbar menu doesn't show at the correct position

### ISSUE THREAD

**Issue by ToffeeNeko** [gileli121/WindowTop#49]
Version: 4.0.3, Pro in trail, using Modern UI

This problem hasn't happened until upgraded to 4.0 version. When moving mouse to the top center of  a window, the green arrow appears, that's fine. However after that nothing else happens when mouse hovering on the arrow, or left clicking on it. ('Save configuration' works well when right clicking the green arrow).

(The round icon is my cursor)
![image](https://user-images.githubusercontent.com/53738915/96359435-7bbe9500-10d8-11eb-9c51-48dd4a4dd209.png)

**Comment by ToffeeNeko** [comment]
Supplement: Menu comes out normally with modern mode disabled.

**Comment by gileli121** [comment]
Hi, there was a regression in v4.0.3 that caused by fixing issue #48 
Please download v4.1.0 instead and let me know if it fixed.

### v4.1.0
* Added: Chinese language to the modern toolbar
* Fixed: Some regression bug in v4.0.3

**Comment by ToffeeNeko** [comment]
Updated to v4.1.0, still have the same problem. Tried both installed an portable version.

**Comment by ToffeeNeko** [comment]
BTW my display resolution is 3840*2160, maybe there's compatible problem with high resolution?

**Comment by gileli121** [comment]
Sorry about your issue.
Can you please do the following steps on the installed version?

1. Go to %appdata%\WindowTop
![image](https://user-images.githubusercontent.com/17680514/96360643-894f3b80-1127-11eb-90d3-b91a0ec2f7f6.png)

2. Send me the "WindowTop.settings" to gileli121@gmail.com
![image](https://user-images.githubusercontent.com/17680514/96360645-95d39400-1127-11eb-9ca1-1b2be88c75c9.png)

After you did it, try also to delete this file and then restart WindowTop
I would like to know if it changed the buggy behavior.
Do it only after you sent me this file.

Thanks

**Comment by ToffeeNeko** [comment]
Setting file sent. I've tried deleting this file and restart/reinstall WindowTop, but problem remains.

**Comment by gileli121** [comment]
Can you try please with this version:
https://github.com/gileli121/WindowTop/releases/download/v4.0/WindowTop.Portable.v4.0.0.2.zip
?

**Comment by ToffeeNeko** [comment]
Same problem😂

**Comment by gileli121** [comment]
Can you try please to change DPI scaling to 100% and resolution to 1920x1080 like in the screenshot:
![image](https://user-images.githubusercontent.com/17680514/96360866-979e5700-1129-11eb-816b-ace69e614a45.png)

Then sign out and sign in again?

**Comment by ToffeeNeko** [comment]
Oh I find what's going wrong. the menu actually appears, but it's far away in the right instead of under the arrow. After moving the arrow to top left I can see the menu. It's blinking and the distance between arrow and menu is dependent on the position of arrow.

![image](https://user-images.githubusercontent.com/53738915/96361002-93514a00-10e7-11eb-8bc5-62a4488adb13.png)
![image](https://user-images.githubusercontent.com/53738915/96361010-a7954700-10e7-11eb-8424-7eaf32ac78ba.png)
![image](https://user-images.githubusercontent.com/53738915/96361019-b54acc80-10e7-11eb-925c-85d8f003f80c.png)

**Comment by gileli121** [comment]
Thanks, it is DPI issue.
If it will set to 100% (not an option for 4k resolution) than the problem will go away.
I was able to reproduce your issue.

Thanks for the report.
I will work on fix soon.

For now, you can try to reduce DPI to 100% and reduce the resolution to 1920x1080 if you want.. but I will understand if you don't want to do it.
The other option is to disable for now the modern menu option.

**Comment by ToffeeNeko** [comment]
😂😂😂Glad to to help with catching some bugs. Actually there are also some other problems like responding extremely slowly when I want to change settings and compatible problem with high resolution (transparent mode and dark mode). WindowTop is a great tool and I'd like to pay for it if these defects could be fixed.. 

Anyway, waiting for your good news.

**Comment by gileli121** [comment]
The other problem you mentioned is listed in the download page under title "Important Known Issues".
I know that the dark mode and smart transparency mode works slow on 4k. I will try to fix it when I get time for it.
I will add this problem also to the list

**Comment by gileli121** [comment]
@ToffeeNeko 
Hi, this is not a full fix yet.
Just let me know if it is working better for you -

1. Please download this file:
[WindowTopUI.zip](https://github.com/gileli121/WindowTop/files/5397390/WindowTopUI.zip)
2. Extract it and copy the "WindowTopUI.exe" file and place it instead of the original "WindowTopUI.exe" under internal folder.
You can do it on the portable version.

**Comment by gileli121** [comment]
Fixed in v4.1.1
Download from here https://github.com/gileli121/WindowTop/releases/tag/v4

**Comment by ToffeeNeko** [comment]
Works well. Great! 👍
