### ISSUE TITLE
Not working with Citrix Receiver

### ISSUE THREAD

**Issue by karolpiotrowicz** [gileli121/WindowTop#7]
Hi,

I'm using Citrix Receiver software to connect to the VM at my work. I'd like to have a Zoom conference window that is installed on my local machine - always on top. When I set a window to be always on top, and then click Citrix content, the Citrix is always on top.

**Comment by gileli121** [comment]
Hello, 
Thanks for the report.
Unforchantly I did not understand your issue.

Can you please describe the scenario in the following format:

- Use Citrix Receiver client xxx from xxx
- Use zoom  

**Steps**
1. Open Citrix Receiver client 
2. Do x
3. Do y
...

*Expected*
Your expected behavior

*Actual*
Actual behavior


Thanks

**Comment by karolpiotrowicz** [comment]
Hi,

Sorry for being not specific enough. When you open a Citrix client, and you
connect to your VM - you can enable the full screen mode like with many
other apps, to have "almost like on your local machine" experience. What
I'm doing now is:

- open citrix client
- set the zoom window as "always on top" by the shortcut alt + z
- maximize citrix client (zoom window is on top)
- click anything in the citrix client (zoom window goes immediately under).

I've tried multiple apps, and none of them works.

Regards,
Karol

czw., 16 kwi 2020 o 18:18 Gil Eliyahu <notifications@github.com> napisał(a):

**Comment by gileli121** [comment]
Thanks,
It looks from your description that the problem is not related to Citrix client but only to zoom.
Or you are saying that the window stops to be on top only when you use the Citrix client window?

**Comment by karolpiotrowicz** [comment]
Hi,

The problem exists with all application. I've tried system applications
(such as calc), graphical (photoshop) and office applications (word and
onenote).

Regards,
Karol

czw., 16 kwi 2020 o 19:00 Gil Eliyahu <notifications@github.com> napisał(a):

**Comment by karolpiotrowicz** [comment]
And yes - the applications are no longer "on top" when I start using Citrix
client.

czw., 16 kwi 2020 o 19:03 Karol Piotrowicz <karol.piotrowicz@gmail.com>
napisał(a):

**Comment by gileli121** [comment]
To be sure I understand, when you don't use the `Citrix` app, you don't have the issue right?

**Comment by karolpiotrowicz** [comment]
Exactly. Everything is fine, except when using Citrix App. It seems that
Citrix App is always on top, no matter what I do.

czw., 16 kwi 2020 o 19:14 Gil Eliyahu <notifications@github.com> napisał(a):

**Comment by gileli121** [comment]
Thanks for clarifying the issue. 
It sounds that this Citrix client unset any top-most window. It is not a problem in Zoom, it is a problem with Citrix that unset other windows on top.

In this case, I will try to add a logic in WindowTop that will check if the window was unset from the top and if it happened, it will set it back.

I will send you an experimental version.
I can't reproduce the issue on my side because I don't have an account on Citrix but based on the information you provided I will try to build a solution and you will test it.

**Comment by karolpiotrowicz** [comment]
That'd be really nice. I actually saw some people looking for solution to
that issue over the internet. Other use case is a company using VM's and
Citrix connectivity, and they also want to have a window from the IP Camera
displayed (monitoring the reception). And the IP Camera window is from
local machine.

Regards,
Karol

czw., 16 kwi 2020 o 19:32 Gil Eliyahu <notifications@github.com> napisał(a):

**Comment by gileli121** [comment]
Hello,
The issue should be fixed now.
Please download this `WindowTop.exe` file and put it instead of `WindowTop.exe` under location `C:\Program Files\WindowTop`

Here is the new file:

[WindowTop v3.3.8.1.zip](https://github.com/gileli121/WindowTop/files/4506130/WindowTop.v3.3.8.1.zip)


Please let me know if it was fixed for you.
Thanks!

**Comment by karolpiotrowicz** [comment]
Hi,

Still doesn't work  ;/ do you want me to record a video of my screen?

Regards,
Karol

pon., 20 kwi 2020, 22:59 użytkownik Gil Eliyahu <notifications@github.com>
napisał:

**Comment by gileli121** [comment]
Yes, please send video

**Comment by gileli121** [comment]
@karolpiotrowicz 
Maybe you can try again with v5
https://github.com/gileli121/WindowTop/tree/v5.x.x
I did not tried to fix this bug but I rewrote the software in C#.
Maybe somehow I did it right so you will not have this issue.

Anyway, for now I will close it.
Feel free to report if you still have the issue
